version: '3.9'

services:
  demo-server:
    container_name: demo-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fudo_db_docker
    env_file:
      - .env

  fudo_db_docker:
    image: postgres:15.1
    container_name: fudo_db_docker
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql-volume:


